apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: party-booking
  labels:
    app: party-booking
    name: party-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: party-booking
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: party-booking
    spec:
      containers:
        - image: party-booking
          name: party-booking
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 8080
status: {}