CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	email varchar(255) not null,
	UNIQUE (email)
);

create sequence person_sequence start with 1 increment by 1;


CREATE TABLE USER_ADDRESS (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) not null,
	street varchar(255) not null
);

create sequence address_sequence start with 1 increment by 1;